package com.cyberark;

import org.graphwalker.core.machine.ExecutionContext;

/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */
public class SomeSmallTest extends ExecutionContext implements SmallTest {

  Target target = null;

  @Override
  public void e_FirstAction() {
    System.out.println("Running: e_FirstAction");
    target.setColorToRed();
  }

  @Override
  public void e_AnotherAction() {
    System.out.println("Running: e_AnotherAction");
    target.setColorToGreen();
  }

  @Override
  public void e_SomeAction() {
    System.out.println("Running: e_SomeAction");
    target.setColorToRed();
  }

  @Override
  public void e_SomeOtherAction() {
    System.out.println("Running: e_SomeOtherAction");
    target.setColorToGreen();
  }

  @Override
  public void v_VerifyInitialState() {
    System.out.println("Running: v_VerifyInitialState");
    target = new Target();
    assert(target.getCurColor() == Target.Color.GREEN);
  }

  @Override
  public void v_VerifyFirstAction() {
    System.out.println("Running: v_VerifyFirstAction");
    assert(target.getCurColor() == Target.Color.RED);
  }

  @Override
  public void v_NewVertex() {
    System.out.println("Running: v_NewVertex");
    assert(target.getCurColor() == Target.Color.GREEN);
  }
}
